export const IMAGES = {
  hero: {
    lightMode: '/images/hero/light-mode.webp',
    darkMode:  '/images/hero/dark-mode.webp',
    video:     '/images/hero/hero-video.mp4',
  },
  about: {
    hero:         '/images/about/hero.webp',
    construction: '/images/about/pool-construction.webp',
  },
  services: {
    swimmingPool:       '/images/services/hub/swimming-pool.webp',
    turnkeyHero:        '/images/services/turnkey-projects/hero.webp',
    accessoriesHero:    '/images/services/accessories/hero.webp',
    accessoriesLadder:  '/images/services/accessories/ladder.jpg',
    skimmerEdge:        '/images/services/accessories/standard-skimmer-edge.webp',
    overflowEdge:       '/images/services/accessories/deck-level-overflow-edge.webp',
    renovationHero:     '/images/services/renovation/hero.webp',
    renovation:         [
      '/images/services/renovation/1.webp',
      '/images/services/renovation/2.webp',
      '/images/services/renovation/3.webp',
    ],
    readymadeHero:      '/images/services/readymade-pools/hero.webp',
    readymadeAdvantages: [
      '/images/services/readymade-pools/Advantage-01.webp',
      '/images/services/readymade-pools/Advantage-02.webp',
      '/images/services/readymade-pools/Advantage-03.webp',
      '/images/services/readymade-pools/Advantage-04.webp',
      '/images/services/readymade-pools/Advantage-05.webp',
    ],
  },
  poolTypes: {
    private:      '/images/pool-types/private.webp',
    commercial:   '/images/pool-types/commercial.webp',
    recreational: '/images/pool-types/recreational.webp',
    competition:  '/images/pool-types/competition.webp',
    vanishingEdge:'/images/pool-types/vanishing-edge.webp',
    overflow:     '/images/pool-types/overflow.webp',
    skimmer:      '/images/pool-types/skimmer.png',
    readymade:    '/images/pool-types/readymade.webp',
  },
  gallery: {
    light: [
      '/images/gallery/light/gallery-01.webp',
      '/images/gallery/light/gallery-02.webp',
      '/images/gallery/light/gallery-03.webp',
      '/images/gallery/light/gallery-04.webp',
      '/images/gallery/light/gallery-05.webp',
      '/images/gallery/light/gallery-06.webp',
      '/images/gallery/light/gallery-07.webp',
      '/images/gallery/light/gallery-08.webp',
      '/images/gallery/light/gallery-09.webp',
      '/images/gallery/light/gallery-10.webp',
    ],
    dark: [
      '/images/gallery/dark/gallery-01.webp',
      '/images/gallery/dark/gallery-02.webp',
      '/images/gallery/dark/gallery-03.webp',
      '/images/gallery/dark/gallery-04.webp',
      '/images/gallery/dark/gallery-05.webp',
      '/images/gallery/dark/gallery-06.webp',
      '/images/gallery/dark/gallery-07.webp',
      '/images/gallery/dark/gallery-08.webp',
      '/images/gallery/dark/gallery-09.webp',
      '/images/gallery/dark/gallery-10.webp',
    ],
  },
  equipment: {
    hero:                 '/images/products/equipment-catalogue/hero.webp',
    fSeries:              '/images/products/equipment-catalogue/filters/f-series.webp',
    bSeries:              '/images/products/equipment-catalogue/filters/b-series.webp',
    mSeries:              '/images/products/equipment-catalogue/filters/m-series.webp',
    msSeries:             '/images/products/equipment-catalogue/filters/ms-series.webp',
    mxbSeries:            '/images/products/equipment-catalogue/pumps/mxb-series.webp',
    mrbSeries:            '/images/products/equipment-catalogue/pumps/mrb-series.webp',
    mtxSeries:            '/images/products/equipment-catalogue/pumps/mtx-series.webp',
    minderchlor:          '/images/products/equipment-catalogue/disinfection/minderchlor-salt-chlorinator.webp',
    chemicalTabletFeeder: '/images/products/equipment-catalogue/disinfection/chemical-tablet-feeder.webp',
    dosingstar:           '/images/products/equipment-catalogue/disinfection/dosingstar-dosing-pump.webp',
    bpSeries:             '/images/products/equipment-catalogue/disinfection/bp-series.webp',
    hydrosmart:           '/images/products/equipment-catalogue/disinfection/hydrosmart-pool.webp',
    poolVacuum:           '/images/products/equipment-catalogue/disinfection/pool-vacuum.webp',
    heavyDutyVacuumHead:  '/images/products/equipment-catalogue/disinfection/heavy-duty-ss-vacuum-head.webp',
    aluminumVacuumHead:   '/images/products/equipment-catalogue/disinfection/aluminum-head-14.webp',
    vacuumHeadSideBrush:  '/images/products/equipment-catalogue/disinfection/vacuum-head-side-brush.webp',
    ssAlgaeBrushes:       '/images/products/equipment-catalogue/disinfection/ss-algae-brushes.webp',
    polesWithGripLock:    '/images/products/equipment-catalogue/disinfection/poles-with-grip-lock.webp',
    poolHose:             '/images/products/equipment-catalogue/disinfection/pool-hose.webp',
    poolPlastic:          '/images/products/equipment-catalogue/disinfection/pool-plastic.webp',
    poolGeneral:          '/images/products/equipment-catalogue/disinfection/pool-general.webp',
  },
  tilesHero: '/images/services/pool-tiles/hero.webp',
  tiles: [
    '/images/services/pool-tiles/1.webp',
    '/images/services/pool-tiles/2.webp',
    '/images/services/pool-tiles/3.webp',
    '/images/services/pool-tiles/4.webp',
    '/images/services/pool-tiles/5.webp',
    '/images/services/pool-tiles/6.webp',
    '/images/services/pool-tiles/7.webp',
    '/images/services/pool-tiles/8.webp',
  ],
  waterFeatures: {
    hero:     '/images/services/water-features/hero.webp',
    geyser:   '/images/services/water-features/geyser-jet-fountain.webp',
    foam:     '/images/services/water-features/foam-jet-fountain.webp',
    bell:     '/images/services/water-features/bell-jet-fountain.webp',
    dandelion:'/images/services/water-features/dandelion.webp',
    bubbler:  '/images/services/water-features/bubbler-jet-fountain.webp',
    curtains: '/images/services/water-features/water-curtains.webp',
    laminar:  '/images/services/water-features/laminar-jets.webp',
    tiered:   '/images/services/water-features/tiered-cascade-fountain.webp',
    musical:  'https://images.unsplash.com/photo-1510006851064-e6056cd0e3a8?auto=format&fit=crop&w=800&q=80',
  },
  specialty: {
    hero: '/images/products/specialty-installations/hero.webp',
    adhesiveGrout: [
      '/images/products/specialty-installations/adhesive-grout/1.webp',
      '/images/products/specialty-installations/adhesive-grout/2.webp',
      '/images/products/specialty-installations/adhesive-grout/3.webp',
      '/images/products/specialty-installations/adhesive-grout/4.webp',
    ],
    sunbath: [
      '/images/products/specialty-installations/sunbath/1.webp',
      '/images/products/specialty-installations/sunbath/2.webp',
      '/images/products/specialty-installations/sunbath/3.webp',
      '/images/products/specialty-installations/sunbath/4.webp',
      '/images/products/specialty-installations/sunbath/5.webp',
    ],
    jacuzzi: [
      '/images/products/specialty-installations/jacuzzi/1.webp',
      '/images/products/specialty-installations/jacuzzi/2.webp',
      '/images/products/specialty-installations/jacuzzi/3.webp',
      '/images/products/specialty-installations/jacuzzi/4.webp',
      '/images/products/specialty-installations/jacuzzi/5.webp',
    ],
  },
  sections: {
    footer:         '/images/sections/footer.webp',
  },
} as const;
